name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
tag-prefix: 'v'
include-pre-releases: false
change-template: '- $TITLE (#$NUMBER) $AUTHORS'
change-title-escapes: '\<*_&'
categories:
  - title: '新增功能'
    exclusive: true
    when:
      labels: ['feature', 'enhancement']
  - title: '问题修复'
    exclusive: true
    when:
      labels: ['fix', 'bugfix', 'bug']
  - title: '文档更新'
    exclusive: true
    when:
      labels: ['docs', 'documentation']
  - title: '其他更新'
template: |
  ## 更新内容

  $CHANGES
